spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.95.215.194:3306/creation-forum?useSSL=false
    username: root
    password: zhanglujie
  redis:
    database: 0
    host: 47.95.215.194
    port: 6379
    password: zhanglujie